"""
first_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
from astro.table import Table, Metadata
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1_task")
def python_1_task_func():
    from datetime import datetime
    
    print(datetime.now())

@aql.dataframe(task_id="python_2_task")
def python_2_task_func():
    import pandas as pd
    
    print(50000/3)

@aql.run_raw_sql(conn_id="duckdb_default", task_id="sql_1", results_format="pandas_dataframe")
def sql_1_func():
    return """
    Select 1 as A, 2 as B, 1/0 As C;
    """

default_args={
    "owner": "michael.l.pupulin@gmail.com,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-06-14", "YYYY-MM-DD").in_tz("EST"),
    catchup=False,
    owner_links={
        "michael.l.pupulin@gmail.com": "mailto:michael.l.pupulin@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clxe24qvw0g6901k6n4qcqewo/cloud-ide/clxe2676c0fzb01mlguaj2fgo/clxe2ah0n0g0701ml8ckenkai",
    },
)
def first_pipeline():
    python_1_task = python_1_task_func()

    python_2_task = python_2_task_func()

    sql_1 = sql_1_func()

    python_2_task << python_1_task

    sql_1 << python_1_task

dag_obj = first_pipeline()
